apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crafty
  namespace: crafty
spec:
  test:
    enable: false
  # values:
  #   common:
  #     fallbackDefaults:
  #       storageClass: standard
