name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup yq
        uses: nivianacd/pkg/actions/yq@main
      - name: Setup kubeconform
        uses: nivianacd/pkg/actions/kubeconform@main
      - name: Setup kustomize
        uses: nivianacd/pkg/actions/kustomize@main
      - name: Validate manifests
        run: bash ./scripts/validate.sh
